services:
  redis:
    image: redis:latest
    ports:
      - "6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/conf:/usr/local/etc/redis
  dept-video-server:
    depends_on: [ "redis" ]
    build: api
    environment:
      JAVA_OPTS:
      APP_OPTS: --spring.data.redis.host=redis
    ports:
      - "8484:8484"
    volumes:
      - ./api/api.jar:/home/app.jar
